Stat svc
dmmitr632/java-explore-with-me pull request #3
Opened 2023-04-20 05:36 UTC by dmmitr632

2023-04-20 21:52 UTC, alexache requested changes

2023-04-20 21:52 UTC, alexache commented on stats-server/pom.xml
> +            <version>2.7.8</version>
Разве требуется еще номер версии спринг библиотеки? В парент модуле уже есть использование спринг парента

2023-04-20 21:52 UTC, alexache commented on stats-server/pom.xml
> +            <version>42.5.4</version>
Для остальных библиотек - все версии зависимости должны быть указаны в родительском модуле через dependencyManagement

2023-04-20 21:52 UTC, alexache commented on stats-server/src/main/java/ru/practicum/stats/controller/StatsController.java
> +    private final EndPointHitServiceImpl endPointHitService;
Тип у поля и у аргумента конструктора должен быть интерфейс (EndPointHitService), а не реализация

2023-04-20 21:52 UTC, alexache commented on stats-server/src/main/java/ru/practicum/stats/service/EndPointHitServiceImpl.java
> +        String app = "main-service";
Это ведь должно приходить в ДТО на вход сервиса статистики?

2023-04-20 21:52 UTC, alexache commented on stats-server/src/main/java/ru/practicum/stats/service/EndPointHitServiceImpl.java
> +            SortedSet<String> urisUniqueSorted = Collections.synchronizedSortedSet(new TreeSet<>(urisUnique));
Для чего здесь синхронизация для коллекции локальной переменной?

2023-04-20 21:52 UTC, alexache commented on stats-server/src/main/java/ru/practicum/stats/service/EndPointHitServiceImpl.java
> +                Collection<EndpointHit> endpointHits = endpointHitRepository.getStatistic(urisUniqueSorted, start, end);
Нельзя ли этот подсчет сделать в SQL запросе?

2023-04-21 14:13 UTC, dmmitr632 commented on stats-server/src/main/java/ru/practicum/stats/service/EndPointHitServiceImpl.java
> +                Collection<EndpointHit> endpointHits = endpointHitRepository.getStatistic(urisUniqueSorted, start, end);
Там же идет как раз запрос к endpointHitRepository, где прописан sql-запрос. Или ты про что-то другое?

2023-04-24 20:21 UTC, alexache requested changes

2023-04-25 20:43 UTC, alexache approved these changes

2023-04-25 21:24 UTC, merged