Main svc
dmmitr632/java-explore-with-me pull request #4
Opened 2023-04-26 18:25 UTC by dmmitr632

2023-05-08 23:22 UTC, alexache requested changes

2023-05-08 23:22 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/EventServiceImpl.java
> +@ComponentScan(basePackages = {"ru.practicum"})
Зачем это здесь?

2023-05-08 23:22 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/EventServiceImpl.java
> +                event.setViews(0);
Почему ноль?

2023-05-08 23:22 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/EventServiceImpl.java
> +        event.setViews(event.getViews() + 1);
Так нельзя делать; это нужно получать через сервис статистик и

2023-05-08 23:22 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/EventServiceImpl.java
> +
Это запрос к базе в цикле, так нельзя делать

2023-05-08 23:22 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/EventServiceImpl.java
> +        events.forEach(e -> e.setViews(e.getViews() + 1));
Такой же комментарий- так нельзя считать просмотры

2023-05-08 23:22 UTC, alexache commented on main-service/src/main/resources/schema.sql
> +    title              VARCHAR(1024)                                NOT NULL,
Это не должно храниться в базе

2023-05-09 03:48 UTC, dmmitr632 commented on main-service/src/main/resources/schema.sql
> +    title              VARCHAR(1024)                                NOT NULL,
Что именно, state?

2023-05-09 10:05 UTC, alexache commented on main-service/src/main/resources/schema.sql
> +    title              VARCHAR(1024)                                NOT NULL,
Нет, я промахнулся строчкой - views

2023-05-11 10:51 UTC, alexache requested changes

2023-05-11 10:51 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/model/Event.java
>      private Integer confirmedRequests;
Не обратил внимание, что и это вынесеено в поле событий. Это значение можно получать запросом в другую таблицу, а потом совершенно излишне хранить в данной таблице

2023-05-11 10:51 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/EventServiceImpl.java
> +                events.stream().map(EventMapper::toEventShortDto).peek(e -> e.setViews((long) getStatisticFromClient(
Это запрос к сервису статистики, так тоже делать нельзя. Нужно получить одним запросом к сервису статистики по списку событий

2023-05-11 10:51 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/EventServiceImpl.java
>          eventFullDto.setConfirmedRequests(
Раз то получается запросом к базе, то зачем оно в таблице событий?

2023-05-11 10:51 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/EventServiceImpl.java
> +                hits = (int) (hits + viewStatsDto.getHits());
А зачем здесь int?

2023-05-11 10:51 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/EventServiceImpl.java
> +            e.getMessage();
Не очень хорошая обработка исключений. Нужно ли продолжать работу, если такое встретилось?

2023-05-11 11:08 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/EventServiceImpl.java
> -        eventShortDtoList.forEach(e -> e.setConfirmedRequests(
А что теперь взамен?

2023-05-11 20:05 UTC, alexache approved these changes

2023-05-11 20:05 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/EventServiceImpl.java
> +        long views = getStatisticFromClient((Collections.singletonList("/events")));
А где список ивент айди? Нужен список URI событий в качестве аргумента

2023-05-11 20:05 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/EventServiceImpl.java
> +        long views = getStatisticFromClient((Collections.singletonList("/admin/events")));
И здесь что-то не то с аргументом, почему здесь не список URI от events?

2023-05-12 21:38 UTC, merged