Feature comments
dmmitr632/java-explore-with-me pull request #5
Opened 2023-05-13 02:53 UTC by dmmitr632

2023-05-14 17:32 UTC, alexache requested changes

2023-05-14 17:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/repository/CommentRepository.java
> +    Integer getUserIdOfComment(Integer commentId);
Почему бы тоже не сделать с помощью имени метода, а не native query? По джоин таблицам это вполне делается

2023-05-14 17:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/CommentServiceImpl.java
> +    public ArrayList<CommentDto> getCommentsAdmin(Integer from, Integer size) {
Лучше List и оставить вместо ArrayList

2023-05-14 17:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/CommentServiceImpl.java
> +        comments.forEach(c -> commentDtoList.add(CommentMapper.toCommentDto(c)));
как-то неканонично. Лучше comments.strean().map(CommentMapper::toCommentDto).collect(Collectors.toList())

2023-05-14 17:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/CommentServiceImpl.java
> +        Event event = eventRepository.findById(eventId).orElseThrow(() -> new NotFoundException("Собтыие не найдено"));
Хорошо бы еще проверять, что этот пользователь посещал данное событие

2023-05-14 17:32 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/EventServiceImpl.java
> +        List<Integer> eventsIds = events.stream().map(Event::getId).collect(Collectors.toList());
Почему бы сразу не сделать лист eventsUris с доп мапом? ВТорой список выглядит излишним

2023-05-14 17:32 UTC, alexache commented on postman/feature.json
> +							"name": "Изменение категории",
Лучшн оставить только те тесты, которые релевантны к данной новой фиче, а не все старые тесты в придачу

2023-05-14 17:38 UTC, dmmitr632 commented on main-service/src/main/java/ru/practicum/ewm/repository/CommentRepository.java
> +    Integer getUserIdOfComment(Integer commentId);
Я сначала так и пытался, но не вышло.

2023-05-14 17:53 UTC, dmmitr632 commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/CommentServiceImpl.java
> +        Event event = eventRepository.findById(eventId).orElseThrow(() -> new NotFoundException("Собтыие не найдено"));
У меня по задумке комментарии можно оставлять под еще не состоявшимся событиями. Пользователь может, например, спрашивать что-нибудь. Или так нельзя?

2023-05-14 23:02 UTC, dmmitr632 commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/CommentServiceImpl.java
> +        Event event = eventRepository.findById(eventId).orElseThrow(() -> new NotFoundException("Собтыие не найдено"));
Сделал так, что писать может только пользователь, утвержденный для события. Насчет посещения, событие не может быть в прошлом или ближайшем настоящем, согласно условию для создания события "Обратите внимание: дата и время на которые намечено событие не может быть раньше, чем через два часа от текущего момента".

2023-05-15 18:04 UTC, alexache commented on main-service/src/main/java/ru/practicum/ewm/service/implementation/CommentServiceImpl.java
> +        Event event = eventRepository.findById(eventId).orElseThrow(() -> new NotFoundException("Собтыие не найдено"));
Ок, пусть будет так, звучит валидно :)

2023-05-15 18:07 UTC, alexache approved these changes

2023-05-15 18:26 UTC, merged